# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    - go mod tidy
    - go mod download
    - go test -v -cover ./...

builds:
  - env:
      - CGO_ENABLED=0
    flags: -trimpath
    ldflags:
      - -X github.com/moyiz/na/cmd.Version={{.Version}}
      - -s
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

aurs:
  - name: na-bin
    homepage: https://github.com/moyiz/na
    description: CLI tool to effortlessly manage context aware nested shortcuts for shell commands.
    license: BSD-3-Clause
    maintainers:
      - moyiz <8603313+moyiz@users.noreply.github.com>
    contributors:
      - moyiz <8603313+moyiz@users.noreply.github.com>
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/na-bin.git
    depends:
      - glibc
    provides:
      - na
    package: |-
      cd ${srcdir}
      install -Dm755 na ${pkgdir}/usr/bin/na
      install -Dm644 LICENSE ${pkgdir}/usr/share/licenses/$pkgname/LICENSE

      declare bash_comp=${pkgdir}/usr/share/bash-completion/completions/
      declare zsh_comp=${pkgdir}/usr/share/zsh/site-functions/
      declare fish_comp=${pkgdir}/usr/share/fish/vendor_completions.d

      mkdir -p ${bash_comp} ${zsh_comp} ${fish_comp}

      ./na completion bash > na.bash
      ./na completion zsh > na.zsh
      ./na completion fish > na.fish

      install -Dm644 ./na.bash ${bash_comp}/na
      install -Dm644 ./na.zsh ${zsh_comp}/_na
      install -Dm644 ./na.fish ${fish_comp}/na.fish

      ./na docs -o ./man
      mkdir -p ${pkgdir}/usr/share/man/man1/
      install -Dm644 ./man/* ${pkgdir}/usr/share/man/man1/
      install -d ${pkgdir}/usr/share
    commit_author:
      name: moyiz
      email: 8603313+moyiz@users.noreply.github.com

brews:
  - name: na
    homepage: https://github.com/moyiz/na
    description: CLI tool to effortlessly manage context aware nested shortcuts for shell commands.
    license: BSD-3-Clause
    skip_upload: false
    folder: Formula
    repository:
      owner: moyiz
      name: homebrew-tap
      branch: master
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      git:
        private_key: "{{ .Env.TAP_DEPLOY_KEY }}"
    post_install: |-
      generate_completions_from_executable(bin/"na", "completion", shells: [:bash, :zsh, :fish])

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-next"
